Add sqlite make-based script
unikraft-upb/scripts pull request #20
Opened 2023-03-31 08:51 UTC by andreasstamos

2023-05-03 15:29 UTC, StefanJum requested changes
Hi @andreasstamos, thank you for this and sorry for the delay.

Besides the comments, can you please add the `Signed-off-by: Your Name <youremail@...> `line at the end of the commit message, and change the commit message to something like make-based: Add app-sqlite (similar to [this one](https://github.com/unikraft-upb/scripts/commit/fe42d87f0ccbfd92f43e6344eda39385c322f97c)).

2023-05-03 15:29 UTC, StefanJum commented on make-based/app-sqlite/do.sh
> +rootfs_9p="$PWD/sql_files"
```suggestion
rootfs_9p="$PWD/files/sql_files"
```
I would create a new directory `files/sql_files` and add a dummy file so the user can test it. You can add the [`script.sql` script here](https://unikraft.org/docs/usage/make_build/#app-sqlite-for-x86_64).

2023-05-05 19:03 UTC, razvand commented
@StefanJum , I forced push to this PR. See if it's OK.

2023-05-05 19:15 UTC, StefanJum approved these changes
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-05-05 19:15 UTC, merged